### ISSUE TITLE
Options created with option group not clickable in mobile

### ISSUE THREAD

**Issue by rahulinaction** [HubSpot/react-select-plus#15] opened 2016-05-10 09:33 UTC
Im a building phonegap app with react where I am using this excellent library. The problem I face is although the options click works for options rendered without opt group on mobile it does not work for options rendered with opt group on mobile. Seems to work on desktop for both. I tried adding the following code 

this.props.onSelect(this.props.option, event); on handleMouseDown function but this does not solve the issue.

**Comment by rahulinaction** [comment] 2016-06-13 07:09
Any headups on this issue

**Comment by TrevorBurnham** [comment] 2016-06-13 18:12
I haven't had a chance to look into this yet. Let me know if you're able to figure out the root cause of the problem on your end.

**Comment by TrevorBurnham** [comment] 2016-10-31 21:10
Closed by #43. I haven't seen any other issues with React Select Plus on mobile devices. Please reopen if you can provide steps to replicate.

**Closed by TrevorBurnham** 2016-10-31 21:10 UTC
